import type { SampleScene } from '../types/resilicity';

export const SAMPLE_SCENES: SampleScene[] = [
  {
    id: 'sample-dense-urban',
    title: '1. Dense Urban Street',
    location: 'High-Density Commercial & Residential Corridor',
    description: 'Narrow canyon street flanked by shopfronts and mid-rise buildings. Extreme heat trap with no tree canopy and high surface thermal absorption.',
    rawImageUrl: '/samples/sample_1_dense_urban.jpg',
    afterImageUrl: '/samples/sample_1_dense_urban.jpg',
    baseScore: 8.4,
    isReliable: true,
    masks: [
      {
        id: 'm-asphalt',
        className: 'road',
        label: 'Asphalt Roadway',
        areaPercentage: 42,
        albedo: 0.09,
        emissivity: 0.94,
        color: '#e11d48',
        polygonPoints: [[10, 60], [90, 60], [98, 98], [2, 98]],
      },
      {
        id: 'm-facades',
        className: 'wall',
        label: 'Building Facades & Shopfronts',
        areaPercentage: 45,
        albedo: 0.20,
        emissivity: 0.90,
        color: '#d97706',
        polygonPoints: [[0, 0], [45, 0], [40, 65], [0, 65]],
      },
      {
        id: 'm-sky',
        className: 'sky',
        label: 'Sky View (Restricted)',
        areaPercentage: 13,
        albedo: 0.30,
        emissivity: 0.95,
        color: '#38bdf8',
        polygonPoints: [[45, 0], [65, 0], [60, 25], [45, 25]],
      },
    ],
    interventions: [
      {
        id: 'int-tree-canopy',
        type: 'tree_canopy',
        title: 'Shade Tree Canopy',
        targetRegion: 'sidewalk',
        priority: 1,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 1.8,
        description: 'Slender columnar canopy trees along pedestrian curbs without blocking storefronts.',
        promptTemplate: 'slender native shade trees with green canopies along the pedestrian corridor',
        defaultEnabled: true,
      },
      {
        id: 'int-cool-pavement',
        type: 'cool_pavement',
        title: 'Cool Permeable Pavement',
        targetRegion: 'road',
        priority: 2,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 1.2,
        description: 'High-albedo reflective interlocking pavers replacing dark asphalt.',
        promptTemplate: 'light-colored high-albedo interlocking stone pavers',
        defaultEnabled: true,
      },
      {
        id: 'int-shade-canopy',
        type: 'shade_canopy',
        title: 'Tensile Fabric Shade Canopy',
        targetRegion: 'pedestrian',
        priority: 3,
        estCostTier: 'low',
        estCostText: 'Low cost',
        coolingImpact: 1.4,
        description: 'Lightweight UV-reflective tensile shade sails suspended between buildings over walkways.',
        promptTemplate: 'architectural tensile fabric shade sail suspended over sidewalk',
        defaultEnabled: false,
      },
    ],
  },
  {
    id: 'sample-sidewalk-road',
    title: '2. Street with Sidewalk + Road',
    location: 'Multi-Lane Urban Arterial',
    description: 'Wide roadway with dedicated pedestrian sidewalk and perimeter walls. Excellent potential for continuous double-sided tree canopy and permeable median buffers.',
    rawImageUrl: '/samples/sample_2_sidewalk_road.jpg',
    afterImageUrl: '/samples/sample_2_sidewalk_road.jpg',
    baseScore: 7.6,
    isReliable: true,
    masks: [
      {
        id: 'm-road',
        className: 'road',
        label: 'Asphalt Carriageway',
        areaPercentage: 48,
        albedo: 0.10,
        emissivity: 0.94,
        color: '#e11d48',
        polygonPoints: [[35, 45], [95, 45], [98, 98], [30, 98]],
      },
      {
        id: 'm-sidewalk',
        className: 'sidewalk',
        label: 'Pedestrian Sidewalk',
        areaPercentage: 22,
        albedo: 0.25,
        emissivity: 0.91,
        color: '#3b82f6',
        polygonPoints: [[0, 50], [30, 50], [28, 98], [0, 98]],
      },
      {
        id: 'm-veg',
        className: 'vegetation',
        label: 'Existing Trees',
        areaPercentage: 15,
        albedo: 0.22,
        emissivity: 0.97,
        color: '#059669',
        polygonPoints: [[15, 10], [45, 10], [40, 50], [20, 50]],
      },
    ],
    interventions: [
      {
        id: 'int-tree-canopy',
        type: 'tree_canopy',
        title: 'Continuous Sidewalk Canopy',
        targetRegion: 'sidewalk',
        priority: 1,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 1.9,
        description: 'Dense deciduous street trees providing continuous pedestrian shade.',
        promptTemplate: 'lush mature canopy street trees along the wide sidewalk',
        defaultEnabled: true,
      },
      {
        id: 'int-cool-pavement',
        type: 'cool_pavement',
        title: 'High-Albedo Road Surface',
        targetRegion: 'road',
        priority: 2,
        estCostTier: 'low',
        estCostText: 'Low cost',
        coolingImpact: 1.1,
        description: 'Light gray solar-reflective roadway coating preserving traffic lanes.',
        promptTemplate: 'light gray solar reflective road pavement coating',
        defaultEnabled: true,
      },
    ],
  },
  {
    id: 'sample-visible-roof',
    title: '3. Building with Visible Roof',
    location: 'Mid-Rise Residential Rooftop View',
    description: 'Elevated perspective clearly exposing expansive flat concrete roofs with water tanks and solar equipment, ideal for green roof & cool roof retrofit.',
    rawImageUrl: '/samples/sample_3_visible_roof.jpg',
    afterImageUrl: '/samples/sample_3_visible_roof.jpg',
    baseScore: 8.1,
    isReliable: true,
    masks: [
      {
        id: 'm-roof',
        className: 'roof',
        label: 'Exposed Flat Concrete Roof',
        areaPercentage: 38,
        albedo: 0.16,
        emissivity: 0.90,
        color: '#eab308',
        polygonPoints: [[20, 25], [95, 25], [98, 70], [15, 70]],
      },
      {
        id: 'm-walls',
        className: 'wall',
        label: 'Building Facades',
        areaPercentage: 35,
        albedo: 0.28,
        emissivity: 0.88,
        color: '#d97706',
        polygonPoints: [[15, 30], [98, 30], [98, 98], [15, 98]],
      },
    ],
    interventions: [
      {
        id: 'int-green-roof',
        type: 'green_roof',
        title: 'Extensive Rooftop Garden',
        targetRegion: 'roof',
        priority: 1,
        estCostTier: 'high',
        estCostText: 'High cost',
        coolingImpact: 2.3,
        description: 'Lush drought-tolerant sedum planting beds and rooftop greenery around utility units.',
        promptTemplate: 'rooftop garden with green sedum planters, shrubs, and living vegetation',
        defaultEnabled: true,
      },
      {
        id: 'int-cool-roof',
        type: 'cool_roof',
        title: 'High-Reflectance Cool Roof',
        targetRegion: 'roof',
        priority: 2,
        estCostTier: 'low',
        estCostText: 'Low cost',
        coolingImpact: 1.6,
        description: 'High-SRI white elastomeric coating on remaining exposed roof surfaces.',
        promptTemplate: 'bright white high-reflectance cool roof membrane coating',
        defaultEnabled: true,
      },
    ],
  },
  {
    id: 'sample-low-vegetation',
    title: '4. Street with Very Little Vegetation',
    location: 'Elevated Metro Transit Viaduct Corridor',
    description: 'Massive concrete overpass viaduct with wide barren road lanes and vast blank concrete walls. Severe urban heat island effect with near-zero shading.',
    rawImageUrl: '/samples/sample_4_low_vegetation.jpg',
    afterImageUrl: '/samples/sample_4_low_vegetation.jpg',
    baseScore: 8.9,
    isReliable: true,
    masks: [
      {
        id: 'm-road',
        className: 'road',
        label: 'Wide Concrete Roadway',
        areaPercentage: 45,
        albedo: 0.18,
        emissivity: 0.92,
        color: '#e11d48',
        polygonPoints: [[0, 65], [100, 65], [100, 100], [0, 100]],
      },
      {
        id: 'm-wall',
        className: 'wall',
        label: 'Concrete Retaining Wall & Viaduct',
        areaPercentage: 35,
        albedo: 0.22,
        emissivity: 0.90,
        color: '#64748b',
        polygonPoints: [[35, 45], [98, 45], [98, 85], [35, 85]],
      },
    ],
    interventions: [
      {
        id: 'int-tree-canopy',
        type: 'tree_canopy',
        title: 'Linear Planting Buffer Trees',
        targetRegion: 'sidewalk',
        priority: 1,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 2.1,
        description: 'Stately shade tree corridor running along the perimeter wall and road shoulder.',
        promptTemplate: 'line of lush mature green trees casting deep shadows along the concrete wall',
        defaultEnabled: true,
      },
      {
        id: 'int-cool-pavement',
        type: 'cool_pavement',
        title: 'Cool Reflective Pavement Treatment',
        targetRegion: 'road',
        priority: 2,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 1.3,
        description: 'Solar-reflective surface micro-surfacing for the wide roadway.',
        promptTemplate: 'light gray solar reflective road pavement coating',
        defaultEnabled: true,
      },
      {
        id: 'int-shade-canopy',
        type: 'shade_canopy',
        title: 'Transit Shelter Shading',
        targetRegion: 'pedestrian',
        priority: 3,
        estCostTier: 'low',
        estCostText: 'Low cost',
        coolingImpact: 1.5,
        description: 'Architectural cantilevered shade canopy for pedestrian transit waiting zones.',
        promptTemplate: 'modern architectural steel and wooden slatted pedestrian shade pergola',
        defaultEnabled: false,
      },
    ],
  },
  {
    id: 'sample-commercial-campus',
    title: '5. Campus / Commercial Street',
    location: 'Modern Commercial Boulevard with Paver Walkways',
    description: 'Corporate boulevard with glazed glass facades, modern wide sidewalk, and young saplings. Ideal candidate for high-impact canopy maturation and pedestrian pergolas.',
    rawImageUrl: '/samples/sample_5_commercial_campus.jpg',
    afterImageUrl: '/samples/sample_5_commercial_campus.jpg',
    baseScore: 6.8,
    isReliable: true,
    masks: [
      {
        id: 'm-sidewalk',
        className: 'sidewalk',
        label: 'Paver Sidewalk',
        areaPercentage: 25,
        albedo: 0.30,
        emissivity: 0.90,
        color: '#3b82f6',
        polygonPoints: [[0, 55], [45, 55], [40, 98], [0, 98]],
      },
      {
        id: 'm-road',
        className: 'road',
        label: 'Boulevard Roadway',
        areaPercentage: 40,
        albedo: 0.12,
        emissivity: 0.94,
        color: '#e11d48',
        polygonPoints: [[45, 55], [98, 55], [98, 98], [40, 98]],
      },
      {
        id: 'm-buildings',
        className: 'wall',
        label: 'Glass & Clad Facades',
        areaPercentage: 25,
        albedo: 0.35,
        emissivity: 0.85,
        color: '#6366f1',
        polygonPoints: [[45, 20], [98, 20], [98, 65], [45, 65]],
      },
    ],
    interventions: [
      {
        id: 'int-tree-canopy',
        type: 'tree_canopy',
        title: 'Full Canopy Maturation',
        targetRegion: 'sidewalk',
        priority: 1,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 2.0,
        description: 'Expand existing saplings into a broad, interlocking shade canopy covering the walkway.',
        promptTemplate: 'magnificent mature broadleaf shade trees forming a full continuous green canopy over walkway',
        defaultEnabled: true,
      },
      {
        id: 'int-shade-canopy',
        type: 'shade_canopy',
        title: 'Modern Timber Pergola',
        targetRegion: 'pedestrian',
        priority: 2,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 1.4,
        description: 'Warm timber and steel pedestrian pergola along the campus sidewalk edge.',
        promptTemplate: 'contemporary minimalist timber pergola with climbing greenery providing pedestrian shade',
        defaultEnabled: true,
      },
    ],
  },
];
