import type { SampleScene } from '../types/resilicity';

export const SAMPLE_SCENES: SampleScene[] = [
  {
    id: 'north-loop-sample',
    title: 'North Loop / sample',
    location: 'North Loop District',
    description: 'The scene is dominated by hard, low-albedo surfaces. Start with roof reflectance and shade at the pedestrian edge.',
    rawImageUrl: '/samples/urban_street_before.png',
    afterImageUrl: '/samples/urban_street_after.png',
    baseScore: 6.9,
    isReliable: true,
    masks: [
      {
        id: 'm-asphalt',
        className: 'road',
        label: 'Asphalt / road',
        areaPercentage: 34,
        albedo: 0.08,
        emissivity: 0.94,
        color: '#e11d48',
        polygonPoints: [[10, 60], [90, 60], [98, 98], [2, 98]],
      },
      {
        id: 'm-concrete',
        className: 'wall',
        label: 'Concrete / walls',
        areaPercentage: 26,
        albedo: 0.22,
        emissivity: 0.88,
        color: '#d97706',
        polygonPoints: [[0, 0], [40, 0], [35, 55], [0, 55]],
      },
      {
        id: 'm-roofs',
        className: 'roof',
        label: 'Roof surfaces',
        areaPercentage: 18,
        albedo: 0.14,
        emissivity: 0.90,
        color: '#eab308',
        polygonPoints: [[40, 0], [100, 0], [100, 45], [50, 45]],
      },
      {
        id: 'm-veg',
        className: 'vegetation',
        label: 'Vegetation',
        areaPercentage: 16,
        albedo: 0.25,
        emissivity: 0.97,
        color: '#059669',
        polygonPoints: [[75, 45], [98, 45], [98, 65], [75, 65]],
      },
      {
        id: 'm-shade',
        className: 'pavement',
        label: 'Open / shade',
        areaPercentage: 6,
        albedo: 0.35,
        emissivity: 0.95,
        color: '#0d9488',
        polygonPoints: [[45, 45], [75, 45], [75, 60], [45, 60]],
      },
    ],
    interventions: [
      {
        id: 'int-cool-roof',
        type: 'cool_roof',
        title: 'Cool roof coating',
        targetRegion: 'roof',
        priority: 1,
        estCostTier: 'low',
        estCostText: 'Low cost',
        coolingImpact: 0.7,
        description: 'Reflective finish on exposed roof surfaces',
        promptTemplate: 'reflective white cool roof coating',
        defaultEnabled: true,
      },
      {
        id: 'int-tree-canopy',
        type: 'tree_canopy',
        title: 'Tree canopy',
        targetRegion: 'sidewalk',
        priority: 2,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 1.1,
        description: 'Native canopy along the pedestrian edge',
        promptTemplate: 'lush green native canopy trees',
        // Assumption for the scenario: ~5% of the scene's built surface becomes tree canopy. Adjust to your plan.
        landCoverShift: { f_built: -0.05, f_tree: 0.05 },
        defaultEnabled: true,
      },
      {
        id: 'int-cool-pavement',
        type: 'cool_pavement',
        title: 'Cool pavement',
        targetRegion: 'road',
        priority: 3,
        estCostTier: 'med',
        estCostText: 'Medium cost',
        coolingImpact: 0.6,
        description: 'High-albedo surface treatment for walkways and roads',
        promptTemplate: 'light gray cool pavement coating',
        defaultEnabled: false,
      },
    ],
  },
];
